apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: masabot
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: "2"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "16Gi"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Start ollama server in background
              ollama serve &
              sleep 5
              echo "⚡ Preloading model mistral:7b-instruct-v0.2-q4_0 ..."
              ollama pull mistral:7b-instruct-v0.2-q4_0 || true
              # Warm-up run so model is cached
              ollama run mistral:7b-instruct-v0.2-q4_0 --prompt "Hello" || true
              wait
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-data
