{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      name: http
