{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: masabot-ui
  annotations:
{{- toYaml .Values.ui.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ui.ingress.className }}
  rules:
  - host: {{ .Values.ui.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: masabot-ui
            port:
              number: {{ .Values.ui.service.port }}
{{- end }}
