apiVersion: v1
kind: Service
metadata:
  name: masabot-ui
  annotations:
{{- toYaml .Values.ui.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: masabot-ui
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
